name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node Version Manager
        run: npm install -g n
      - name: Set N_PREFIX
        run: echo "N_PREFIX=$HOME/.n" >> $GITHUB_ENV
      - name: Remove node_modules
        run: rm -rf node_modules
      - name: yarn install
        run: yarn install
      - name: build
        run: yarn run build
      - name: GitHub Pages
        if: success()
        with:
          target_branch: gh-pages
          build_dir: public
        uses: crazy-max/ghaction-github-pages@v1.2.5
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          GITHUB_PAT: ${{ secrets.ACCESS_TOKEN }}
