name: gatsby deploy

# main에 push 할때마다 아래 작업을 실행
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: packages install
        run: yarn install

      - name: gatsby build
        run: yarn build
        env:
          GH_API_KEY: ${{ secrets.ACCESS_TOKEN }}

      - name: deploy
        uses: peaceiris/actions-gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.ACCESS_TOKEN }}
          BUILD_DIR: 'public/'
